# transaction-management-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: transaction-management-service
  labels:
    app: transaction-management
    version: "{{APP_VERSION}}"
spec:
  selector:
    app: transaction-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP